version: '3.8'

services:
  # Flask web application
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - db

  # MySQL database service
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: village_blog
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

# Named volumes to persist MySQL data
volumes:
  mysql_data:

